// Generates random names
"use strict";

const NameGenerator = module.exports = {};

const name_list = [
	"Aardwolf",
	"Ahmet Abdol",
	"Abner Little",
	"Abominable Snowman",
	"Abomination",
	"Abominatrix",
	"Abraxas",
	"Absalom",
	"Absorbing Man",
	"Abyss",
	"Access",
	"Achebe",
	"Achelous",
	"Achilles",
	"Acrobat",
	"Adam II",
	"Adam X",
	"Adaptoid",
	"Administrator",
	"Adonis",
	"Adrenazon",
	"Adversary",
	"Advisor",
	"Aegis",
	"Aero",
	"Jamal Afari",
	"Aftershock",
	"Agamemnon",
	"Agamotto",
	"Aged Genghis",
	"Agent",
	"Agent Axis",
	"Agent Cheesecake",
	"Agent X",
	"Agent Zero",
	"Aginar",
	"Aggamon",
	"Agon",
	"Agron",
	"Agony",
	"El Aguila",
	"Aguja",
	"Ahab",
	"Ahura",
	"Air-Walker",
	"Airborne",
	"Aireo",
	"Airstrike",
	"Ajak",
	"Ajax",
	"Ajaxis",
	"Akasha",
	"Akhenaten",
	"A'lars",
	"Alaris",
	"Albert",
	"Albino",
	"Albion",
	"Alchemy",
	"Alcmena",
	"Aldebron",
	"Alex",
	"Caleb Alexander",
	"Carrie Alexander",
	"Algrim the Strong",
	"Abdul Alhazred",
	"Alibar",
	"Alistair Smythe",
	"Alistaire Stuart",
	"Aliyah Bishop",
	"Alkhema",
	"All-American",
	"Liz Allan",
	"Allatou",
	"St. John Allerdyce",
	"Alpha Ray",
	"Alpha the Ultimate Mutant",
	"Marlene Alraune",
	"Alysande Stuart",
	"Alyssa Moy",
	"Amalgam",
	"Amanda Sefton",
	"Amatsu-Mikaboshi",
	"Amazon",
	"Amber Hunt",
	"Amelia Voght",
	"Amergin",
	"American Ace",
	"American Dream",
	"American Eagle",
	"American Samurai",
	"Americop",
	"Ameridroid",
	"Amiko Kobayashi",
	"Amina Synge",
	"Aminedi",
	"Ammo",
	"Amphibian",
	"Amphibion",
	"Amphibius",
	"Amun",
	"Anaconda",
	"Anais",
	"Analyzer",
	"Anarchist",
	"Ancient One",
	"Tanya Anderssen",
	"Andreas von Strucker",
	"Andrew Chord",
	"Andrew Gervais",
	"Android Man",
	"Andromeda",
	"Anelle",
	"Angar the Screamer",
	"The Angel",
	"Angel",
	"Angel Dust",
	"Angel Face",
	"Angel Salvadore",
	"Angela Cairn",
	"Angela Del Toro",
	"Angler",
	"Ani-Mator",
	"Animus",
	"Animus",
	"Ankhi",
	"Annalee",
	"Anelle",
	"Anne-Marie Cortez",
	"Annex",
	"Annie Ghazikhanian",
	"Annihilus",
	"Anole",
	"Anomalito",
	"Anomaloco",
	"Anomaly",
	"Answer",
	"Ant-Man",
	"Anthropomorpho",
	"Anti-Cap",
	"Anti-Phoenix Force",
	"Anti-Venom",
	"Anti-Vision",
	"Antimatter",
	"Antiphon the Overseer",
	"Antonio",
	"Anything",
	"Anubis",
	"Anvil",
	"Apache Kid",
	"Apalla",
	"Ape",
	"Ape-Man",
	"Ape-X",
	"Apocalypse",
	"Apollo",
	"Apryll",
	"Aquarian",
	"Aquarius",
	"Aqueduct",
	"Arabian Knight",
	"Arachne",
	"Aragorn",
	"Araki",
	"Aralune",
	"Araña",
	"Arc",
	"Arcade",
	"Arcademan",
	"Arcanna",
	"Archangel",
	"Archenemy",
	"Archer",
	"Archie Corrigan",
	"Archimage",
	"Architect",
	"Arclight",
	"Arcturus Rann",
	"Ardina",
	"Ardroman",
	"Arena",
	"Ares",
	"Argo",
	"Argus",
	"Ariann",
	"Arides",
	"Ariel",
	"Aries",
	"Arishem the Judge",
	"Arizona Annie",
	"Arize",
	"Arkon",
	"Arkus",
	"Todd Arliss",
	"Arlok",
	"Armadillo",
	"Armageddon",
	"Armand Martel",
	"Armor",
	"Armory",
	"Arnim Zola",
	"the Renegade Watcher Aron",
	"Arranger",
	"Arsenal",
	"Arsenic",
	"Artemis",
	"Artie",
	"Arturo Falcones",
	"Jackson Arvad",
	"Asbestos Lady",
	"Asbestos Man",
	"Ashcan",
	"Asmodeus",
	"Asp",
	"Assassin",
	"Astaroth / Asteroth",
	"Astra",
	"Astrid Bloom",
	"Vance Astrovik",
	"Astron",
	"Astronomer",
	"Asylum",
	"Atalanta",
	"Atalon",
	"Atlas",
	"Atlas",
	"Atlas",
	"Athena",
	"Atleza",
	"Atom Bob",
	"Atom-Smasher",
	"Att-Lass",
	"Attuma",
	"Atum",
	"Aunt May Parker",
	"Auntie Freeze",
	"Auric",
	"Aurora",
	"Authority",
	"Autolycus",
	"Avalanche",
	"Avarrish",
	"Awesome Android",
	"Axum",
	"Azazel",
	"Baal",
	"Gailyn Bailey",
	"Joey Bailey",
	"Paul Bailey",
	"Sunset Bain",
	"William Baker",
	"Balder",
	"Balthakk",
	"Balor",
	"Bandit",
	"Bantam",
	"Betty Ross Banner",
	"Robert Bruce Banner",
	"Banshee",
	"Baphomet",
	"Barbarus",
	"Barnacle",
	"Baron Blood",
	"Baron Brimstone",
	"Baron Macabre",
	"Baron Mordo",
	"Baron Samedi",
	"Baron Strucker",
	"Baron Zemo",
	"Baroness Blood",
	"Barracuda",
	"Clint Barton",
	"Base",
	"Basilisk",
	"Bast",
	"Bastion",
	"Ruth Bat-Seraph",
	"Batragon",
	"Batroc the Leaper",
	"Battering Ram",
	"Battlestar",
	"Battleaxe",
	"Battletide",
	"Batwing",
	"Jean-Paul Beaubier",
	"Jeanne-Marie Beaubier",
	"Beast",
	"Beautiful Dreamer",
	"Benny Beckley",
	"Bedlam",
	"Bedlam II",
	"Jerome Beechman",
	"Beetle",
	"Beetle II",
	"Behemoth",
	"Bela",
	"Belasco",
	"Bella Donna",
	"Belathauzer",
	"Morris Bench",
	"Bengal",
	"Bereet",
	"Berzerker",
	"Bes",
	"Beta Ray Bill",
	"Betty Ross Banner",
	"Bevatron",
	"Beyonder",
	"Bi-Beast",
	"Bible John",
	"Big Bertha",
	"Big Man",
	"Big Wheel",
	"Bill Foster",
	"Binary",
	"Bird-Brain",
	"Bird-Man",
	"Douglas Birely",
	"Bishop",
	"Kate Bishop",
	"Bison",
	"Bizarnage",
	"Blackbird",
	"Carmilla Black",
	"Black Bolt",
	"Black Box",
	"Black Cat",
	"Black Crow",
	"Black Death",
	"Black Dragon",
	"Black Fox",
	"Black Goliath",
	"Blackheart",
	"Blackheath",
	"Black Jack Tarr",
	"Black King",
	"Black Knight",
	"Blacklash",
	"Black Lama",
	"Black Mamba",
	"Black Marvel",
	"Blackout",
	"Black Panther",
	"Black Queen",
	"Black Talon",
	"Black Tarantula",
	"Black Tom Cassidy",
	"Black Widow",
	"Blackwing",
	"Blackwulf",
	"Blade",
	"Allison Blaire",
	"The Blank",
	"Blaquesmith",
	"Brass",
	"Blastaar",
	"Blaze",
	"Johnny Blaze",
	"Siena Blaze",
	"Blazing Skull",
	"Sally Blevins",
	"Blind Faith",
	"Blind Justice",
	"Blindside",
	"Blindspot",
	"Bling",
	"Blink",
	"Blistik",
	"Blitziana",
	"Blitzkrieger",
	"Baron Von Blitzschlag",
	"Blizzard",
	"Blizzard II",
	"Blob",
	"Blockbuster",
	"Bloke",
	"Blonde Phantom",
	"Emil Blonsky",
	"Blood Brothers",
	"Blood Rose",
	"Blood Spider",
	"Bloodaxe",
	"Bloodhawk",
	"Bloodlust",
	"Bloodlust II",
	"Bloodscream",
	"Bloodshed",
	"Bloodsport",
	"Bloodstorm",
	"Bloodtide",
	"Bloodwraith",
	"Astrid Bloom",
	"Blowhard",
	"Blue Bullet",
	"Blue Marvel",
	"Blue Diamond",
	"Blue Shield",
	"Blue Streak",
	"Blur",
	"Bob",
	"Bob Diamond",
	"Bobster",
	"Elias Bogan",
	"Bogeyman",
	"Tito Bohusk",
	"Bombshell",
	"Boneyard",
	"Alexander Bont",
	"Boobytrap",
	"Book",
	"Boomer",
	"Boom Boom",
	"Boom Boy",
	"Boomerang",
	"Boomslang",
	"Boost",
	"Bora",
	"Bounty",
	"Bounty Hunter",
	"Bova",
	"Box",
	"Box IV",
	"Brian Braddock",
	"Elizabeth Braddock",
	"Jamie Braddock",
	"Meggan Braddock",
	"Isaiah Bradley",
	"Brain Cell",
	"Brain-Child",
	"Brain Drain",
	"Brainchild",
	"Abigail Brand",
	"Betty Brant",
	"Brass",
	"Bres",
	"George Washington Bridge",
	"Brigade",
	"Briquette",
	"Eddie Brock",
	"Brother Nature",
	"Brother Tode",
	"Brother Voodoo",
	"Brothers Grimm",
	"Abe Brown",
	"Bruiser",
	"Brunnhilda",
	"Brutacus",
	"Brute I",
	"Brute II",
	"Brute III",
	"Brynocki",
	"Bucky",
	"Bucky III",
	"Bug",
	"Bullet",
	"Bullseye",
	"Bulldozer",
	"Bulldozer",
	"Burner",
	"Burstarr",
	"Bushman",
	"Bushmaster",
	"Bushwacker",
	"Butterball",
	"Buzz",
	"Buzzard",
	"Byrrah",
	"Bethany Cabe",
	"Caber",
	"Cable",
	"Cadaver",
	"Luke Cage",
	"Caiera",
	"Caiman",
	"Cagliostro",
	"Cain",
	"Caliban",
	"Callisto",
	"Godfrey Calthrop",
	"Calypso",
	"Heather Cameron",
	"Canasta",
	"Cancer",
	"Candra",
	"David Cannon",
	"Cannonball",
	"Cannonball I",
	"Cap 'N Hawk",
	"Caprice",
	"Capricorn",
	"Captain Atlas",
	"Captain America",
	"Captain Barracuda",
	"Captain Britain",
	"Cap 'N Hawk",
	"Captain Fate",
	"Captain Germany",
	"Captain Marvel",
	"Captain Omen",
	"Captain Savage",
	"Captain Ultra",
	"Captain UK",
	"Captain Universe",
	"Captain Wings",
	"Captain Zero",
	"Caregiver",
	"Caretaker",
	"Cardiac",
	"Cardinal",
	"Carnage",
	"Carnivore",
	"Carolyn Parmenter",
	"Guido Carosella",
	"Carrion",
	"Joe Cartelli",
	"Peggy Carter",
	"Sharon Carter",
	"Cassandra Nova",
	"Sean Cassidy",
	"Theresa Cassidy",
	"Tom Cassidy",
	"Cassiopea",
	"Frank Castle",
	"Cat",
	"Cat-Man",
	"Catiana",
	"Cayman",
	"Cecilia Reyes",
	"Celestial Madonna",
	"Centennial",
	"Centurion",
	"Centurious‎",
	"Centurius",
	"Turner Century",
	"Cerberus",
	"Cerebra",
	"Cerise",
	"Cethlann",
	"Ch'od",
	"Chaka",
	"Challenger",
	"Chamber",
	"Chameleon",
	"Champion of the Universe",
	"Chance",
	"Changeling",
	"Chaos",
	"Charcoal",
	"Charlie-27",
	"Charles Xavier",
	"Charon",
	"Cheetah",
	"Chemistro",
	"Lila Cheney",
	"Chi Demon",
	"Chief Examiner",
	"Chimera",
	"Isaac Christians",
	"Choice",
	"Chondu the Mystic",
	"Chrome",
	"Chronos",
	"Chthon",
	"Chtylok",
	"Citizen V",
	"Clea",
	"Clearcut",
	"Clive",
	"Cloak",
	"Cloud 9",
	"Cloud",
	"Clown",
	"Coach",
	"Coachwhip",
	"Cobalt Man",
	"Cobra",
	"Cody Mushumanski gun Man aka: the hunter",
	"Coldblood",
	"Coldfire",
	"Cold War",
	"Kasper Cole",
	"Colonel America",
	"Collective Man",
	"Collector",
	"Colleen Wing",
	"Rusty Collins",
	"Colonel",
	"Colossus",
	"Comet",
	"Comet Man",
	"Commander Kraken",
	"Commando",
	"Conan the Barbarian",
	"Condor",
	"Curtis Connors",
	"Conquer Lord",
	"Conquest",
	"Conquistador",
	"Constrictor",
	"Contemplator",
	"Contessa",
	"Contrary",
	"Controller",
	"Valerie Cooper",
	"Copperhead",
	"Copperhead",
	"Copycat",
	"Coral",
	"Adrian Corbo",
	"Jared Corbo",
	"Cordelia Frost",
	"Abraham Cornelius",
	"Corona",
	"Corruptor",
	"Corsair",
	"Tom Corsi",
	"Fabian Cortez",
	"Cottonmouth",
	"Courier",
	"Count Abyss",
	"Count Nefaria",
	"Cowgirl",
	"Crazy Eight",
	"Graydon Creed",
	"Victor Creed",
	"Lady Jacqueline Falsworth Crichton",
	"Kenneth Crichton",
	"Crime-Buster",
	"Crimebuster",
	"Crime Master",
	"Crimson",
	"Crimson and the Raven",
	"Crimson Cavalier",
	"Crimson Commando",
	"Crimson Cowl",
	"Crimson Craig",
	"Crimson Daffodil",
	"Crimson Dynamo",
	"Crimson Dynamo V",
	"Crippler",
	"Crooked Man",
	"Crossbones",
	"Crossfire",
	"Crown",
	"Crucible",
	"Crusader",
	"Crusader",
	"Crusher",
	"Crystal",
	"Cutthroat",
	"Cybele",
	"Cybelle",
	"Cyber",
	"Cyborg X",
	"Cyclone",
	"Cyclops",
	"Cypher",
	"Derrick Slegers speed aka: slegers",
	"D'Ken",
	"D'Spayre",
	"Robert da Costa",
	"Dagger",
	"Dakimh the Enchanter",
	"Damballah",
	"Margo Damian",
	"Damon Dran",
	"Lorna Dane",
	"Danger",
	"Danielle Moonstar",
	"Dansen Macabre",
	"Danvers Carol",
	"Daredevil",
	"Dark Angel",
	"Dark Beast",
	"Dark-Crawler",
	"Dark Phoenix",
	"Darkstar",
	"Darkdevil",
	"Darkhawk",
	"Darkoth",
	"Leila Davis",
	"Tex Dawson",
	"Wilbur Day",
	"Daytripper",
	"Dazzler",
	"Dead Girl",
	"Deadhead",
	"Deadly Ernest",
	"Deadpool",
	"Laura Dean",
	"Death",
	"Death Adder",
	"Death's Head I&II",
	"Death's-Head",
	"Deathbird",
	"Deathlok",
	"Deathwatch",
	"Death-Stalker",
	"Deathurge",
	"Deathstroke",
	"Decay",
	"Decay II",
	"Defensor",
	"Valentina Allegra De La Fontaine",
	"Delilah",
	"Delphi",
	"Delphine Courtney",
	"Dementia",
	"Demiurge",
	"Demogoblin",
	"Demogorge the God-Eater",
	"Demolition Man",
	"Destiny I",
	"Destiny",
	"The Destroyer",
	"The Destroyer",
	"Destroyer",
	"Destroyer",
	"Destroyer of Demons",
	"Devastator",
	"Devil Dinosaur",
	"Devil-Slayer",
	"Devos the Devastator",
	"Jean DeWolff",
	"Diablo",
	"Diamanda Nero",
	"Diamond Lil",
	"Diamondback",
	"Diamondhead",
	"Digitek",
	"Maxwell Dillon",
	"Dionysus",
	"Dirtnap",
	"Discus",
	"Dittomaster‎",
	"DJ",
	"D-Man",
	"Dmitri Bukharin",
	"Doc Samson",
	"Doctor Arthur Nagan",
	"Doctor Bong",
	"Doctor Demonicus",
	"Doctor Doom",
	"Doctor Dorcas",
	"Doctor Droom",
	"Doctor Druid",
	"Doctor Faustus",
	"Doctor Glitternight",
	"Doctor Leery",
	"Doctor Minerva‎",
	"Doctor Octopus",
	"Doctor Spectrum",
	"Doctor Strange",
	"Doctor Sun",
	"John Doe",
	"Domina",
	"Dominic Fortune",
	"Domino",
	"Dominus",
	"Domo",
	"Donald Pierce",
	"Donald & Deborah Ritter",
	"Doorman",
	"Doop",
	"Doppelganger",
	"Doppleganger",
	"Dr. Lemuel Dorcas",
	"Dorma",
	"Dormammu",
	"Doug and Jerry",
	"Dougboy",
	"Doughboy",
	"Douglas Ramsey",
	"Douglock",
	"Dracula",
	"Dragon Lord",
	"Dragon Man",
	"Dragon of the Moon",
	"Dragonfly",
	"Dragoness",
	"Dragonwing",
	"Frank Drake",
	"Robert Drake",
	"Drax the Destroyer",
	"Dreadknight",
	"Dreadnought",
	"Dream Weaver",
	"Dreaming Celestial",
	"Dreamqueen",
	"Dredmund Druid",
	"Jessica Drew",
	"Dromedan",
	"Doctor Anthony Droom",
	"Double Helix",
	"Druid",
	"Druid",
	"Druig",
	"Jericho Drumm",
	"Bennet du Paris",
	"Dum-Dum Dugan",
	"Jacques DuQuesne",
	"Dusk",
	"Dust",
	"Sybil Dvorak",
	"Dweller-in-Darkness",
	"Dyna-Mite",
	"Earth Lord",
	"Earthquake",
	"Paul Norbert Ebersol",
	"Ebon Seeker",
	"Ecstasy",
	"Echo",
	"Ectokid",
	"Ethan Edwards",
	"Edwin Jarvis",
	"Eel",
	"Egghead",
	"Ego the Living Planet",
	"El Aguila",
	"El Muerto",
	"Elathan",
	"Electric Eve",
	"Electro",
	"ElectroCute",
	"Electron",
	"Eleggua",
	"Elektra",
	"Elektro",
	"Elf With A Gun",
	"Elfqueen",
	"Eliminator",
	"Eliminator",
	"Elixir",
	"Elsie-Dee",
	"Elven",
	"Elysius",
	"Emma Frost",
	"Empath",
	"Empathoid",
	"Emplate",
	"En Sabah Nur",
	"Enchantress",
	"Energizer",
	"Enforcer",
	"Enigma",
	"Ent",
	"The Entity",
	"Entropic Man",
	"Eon",
	"Epoch",
	"Equilibrius",
	"Equinox",
	"Ereshkigal",
	"Eric the Red",
	"Eric Slaughter",
	"Erg",
	"Ernst",
	"Eros",
	"Eshu",
	"Eson the Searcher",
	"Miguel Espinosa",
	"Mister Sinister",
	"Nathaniel Essex",
	"Eternal Brain",
	"Eternity",
	"Ev Teel Urizen",
	"Evangeline Whedon",
	"Ever",
	"Everyman",
	"Evilhawk‎",
	"Executioner",
	"Exodus",
	"Exploding Man",
	"Exterminator",
	"Ezekiel",
	"Fafnir",
	"Fagin",
	"Falcon",
	"Fallen One",
	"Fantastic Four",
	"Brian Falsworth",
	"Jacqueline Falsworth",
	"John Falsworth",
	"Famine",
	"Fan Boy",
	"Fandral",
	"Fang",
	"Fantasia",
	"Fantomex",
	"Farallah",
	"Hensley Fargus",
	"Amahl Farouk",
	"Fasaud",
	"Fashima",
	"Fatale",
	"Fateball",
	"Father Time",
	"Fault Zone",
	"Fearmaster‎",
	"Feedback",
	"Feline",
	"Fenris",
	"Fenris Wolf",
	"Feral",
	"Fer-de-Lance",
	"Feron",
	"Philip Fetter",
	"Fever Pitch",
	"Fight-Man",
	"Fin",
	"Fin Fang Foom",
	"Firearm",
	"Firebird",
	"Firebolt",
	"Firebrand",
	"Firefrost",
	"Firelord",
	"Firepower",
	"Firestar",
	"Richard Fisk",
	"Wilson Fisk",
	"Trevor Fitzroy",
	"Fixx",
	"Fixer",
	"Flag-Smasher",
	"Flambe",
	"Flash Thompson",
	"Flatman",
	"Flex",
	"Flubber",
	"Marvin Flumm",
	"Fly",
	"Flygirl",
	"Flying Tiger",
	"Foggy Nelson",
	"Fontanelle",
	"Foolkiller",
	"Forbush Man",
	"Force",
	"Forearm",
	"Foreigner",
	"Forge",
	"Forgotten One",
	"Lee Forrester",
	"Don Fortunato",
	"Dominic Fortune",
	"Bill Foster",
	"Jane Foster",
	"Tom Foster",
	"Foxfire",
	"Frank Castle",
	"Frank Drake",
	"Frankenstein's Monster",
	"Frankie and Victoria",
	"Frankie Raye",
	"Franklin Richards",
	"Freak",
	"Freak of Science",
	"Freakmaster",
	"Freakshow",
	"Spike Freeman",
	"Free Spirit",
	"Freedom Ring",
	"Frenzy",
	"Frey",
	"Frigga",
	"Frog-Man",
	"Frog-Man",
	"Adrienne Frost",
	"Deacon Frost",
	"Cordelia Frost",
	"Emma Frost",
	"Rumiko Fujikawa",
	"Fury",
	"Jacob Fury",
	"Nick Fury",
	"Fusion",
	"Futurist",
	"G-Force",
	"Devil Hunter Gabriel",
	"Gabriel the Air-Walker",
	"Gaea",
	"Gaia",
	"Galactus",
	"Galaxy Master",
	"Gambit",
	"Gammenon the Gatherer",
	"Gamora",
	"Ganymede",
	"Gardener",
	"Mac Gargan",
	"Gargantua",
	"Gargantus",
	"Gargouille",
	"Gargoyle",
	"Garokk the Petrified Man",
	"Jonathan Garrett",
	"Sean Garrison",
	"Gatecrasher",
	"Gateway",
	"Gauntlet",
	"Gauntlet",
	"Gavel",
	"Gaza",
	"Gazelle",
	"Gazer",
	"Geb",
	"Gee",
	"Geiger",
	"Geirrodur",
	"Gemini",
	"Genis-Vell",
	"Gertrude Yorkes",
	"Ghaur",
	"Carter Ghazikhanian",
	"Carter Ghazikhanian",
	"Georgianna Castleberry",
	"Ghost",
	"Ghost Dancer",
	"Ghost Girl",
	"Ghost Girl",
	"Ghost Maker",
	"Ghost Rider",
	"Ghost Rider",
	"Ghost Rider 2099",
	"Ghoul",
	"Ghoul",
	"Giant-Man",
	"Gibbon",
	"Gibborim",
	"Kyle Gibney",
	"Gideon",
	"Gregory Gideon",
	"Gideon Mace",
	"Giganto",
	"Gigantus",
	"Donald \"Donny\" Gill",
	"Ritchie Gilmore",
	"Gin Genie",
	"Shi'ar Gladiator",
	"Gladiator",
	"Gladiatrix",
	"Glamor",
	"Glitch",
	"Glob",
	"Glob Herman",
	"Gog",
	"Gloom",
	"Glorian",
	"Goblin Queen",
	"Goblyn",
	"Martin Gold",
	"Melissa Gold",
	"Golden Archer",
	"Goldbug",
	"Goldeneye",
	"Golden Girl",
	"Golden Oldie",
	"Golem",
	"Goliath",
	"Mikula Golubev",
	"Gomi",
	"Googam",
	"Gorgeous George",
	"Gorgilla",
	"Gorgon",
	"Gorilla Girl",
	"Gorilla-Man",
	"Gorr",
	"Gosamyr",
	"Grand Director",
	"Grandmaster",
	"Greer Grant",
	"Grappler",
	"Grasshopper I&II",
	"Graviton",
	"Gravity",
	"Great Gambonnos",
	"Great Video",
	"Green Goblin",
	"Green Goblin IV",
	"Gregory Gideon",
	"Gremlin",
	"Grenade",
	"Elaine Grey",
	"Jean Grey-Summers",
	"Dr. John Grey",
	"Nate Grey",
	"Rachel Grey",
	"Grey Gargoyle",
	"Sara Grey",
	"Grey King",
	"Griffin",
	"Grim Hunter",
	"Grim Reaper",
	"Benjamin Jacob Grimm",
	"The Grip",
	"Grizzly",
	"Grog the God-Crusher",
	"Gronk",
	"Grotesk",
	"Groundhog",
	"Growing Man",
	"Guardsman",
	"Gunthar of Rigel‎",
	"Jebediah Guthrie",
	"Joshua Guthrie",
	"Melody Guthrie",
	"Paige Guthrie",
	"Samuel Guthrie",
	"Gypsy Moth",
	"Henry Peter Gyrich",
	"Hack",
	"Hag",
	"Hairbag",
	"Halflife",
	"Franklin Hall",
	"Thomas Halloway",
	"Halloween Jack",
	"Bart Hamilton",
	"Hamilton Slade",
	"Hammer Harrison",
	"Hammer and Anvil",
	"Justin Hammer",
	"Justine Hammer",
	"Hammerhead",
	"Jim Hammond",
	"Hangman",
	"Hank McCoy",
	"Hank Pym",
	"Hanna Levy",
	"Hannibal King",
	"gen Harada",
	"Hardcase",
	"Hardcore",
	"Hardnose",
	"Hardshell",
	"Hardwire",
	"Felicia Hardy",
	"Hargen the Measurer",
	"Quincy Harker",
	"Agatha Harkness",
	"Harmonica",
	"Harness",
	"Harold H. Harold",
	"Harpoon",
	"Harpy",
	"Harrier",
	"Jonas Harrow",
	"Harry Leland",
	"Harry Osborn",
	"Hate-Monger",
	"Haven",
	"Havok",
	"Hawkeye",
	"Hawkeye II",
	"Hawkshaw",
	"Alex Hayden",
	"Hazard",
	"Molly Hayes",
	"Haywire",
	"Hazmat",
	"Headknocker",
	"Headlok",
	"Heart Attack",
	"Hebe",
	"Hecate",
	"Hector",
	"Heimdall",
	"Hela",
	"Helio",
	"Hellcat",
	"Helleyes",
	"Hellfire",
	"Hellion",
	"Hellion",
	"Hellrazor",
	"Damion Hellstrom",
	"Patsy Hellstrom",
	"Hephaestus",
	"Hepzibah",
	"Her",
	"Hera",
	"H.E.R.B.I.E.",
	"Hercules",
	"Hermes",
	"Hermod",
	"Hero",
	"Hero for Hire",
	"Herr Kleiser",
	"Hideko Takata",
	"High Evolutionary",
	"High-Tech",
	"Hijacker",
	"Hildegarde",
	"Him",
	"Hindsight Lad",
	"Hit-Maker",
	"Hitman",
	"Hobgoblin",
	"Hobgoblin II",
	"Cameron Hodge",
	"Harold \"Happy\" Hogan",
	"Hoder",
	"Hogun",
	"Holocaust",
	"Holly",
	"Honcho",
	"Honey Lemon",
	"Hood",
	"Ned Horrocks",
	"Hornet",
	"Phineas T. Horton",
	"Horus",
	"Howard the Duck",
	"James Howlett",
	"Hrimhari",
	"Hub",
	"Hugh Jones",
	"Hulk",
	"Hulk 2099",
	"Hulkling",
	"Human Cannonball",
	"Human Fly",
	"Human Robot",
	"Human Top I",
	"Human Top II",
	"Human Torch I",
	"Human Torch II",
	"Humbug",
	"Humus Sapien",
	"Huntara",
	"Robert Hunter",
	"Stevie Hunter",
	"Hurricane",
	"Husk",
	"Hussar",
	"Hybrid",
	"Hybrid II",
	"Hyde",
	"Hydro",
	"Hydro-Man",
	"Hydron",
	"Hyperion",
	"Hyperkind",
	"Hyperstorm",
	"Hypnotia",
	"Hyppokri",
	"Hippolyta",
	"Icarus",
	"Iceman",
	"Icemaster",
	"Hisako Ichiki",
	"Idunn",
	"Iguana",
	"Ikaris",
	"Ikonn",
	"Ikthalon",
	"Illusion",
	"Immortus",
	"Impala",
	"Imperial Hydra",
	"Impossible Man",
	"Impulse",
	"In-Betweener",
	"Indra",
	"Indech",
	"Inertia",
	"Infamnia",
	"Infant Terrible",
	"Infectia",
	"Inferno",
	"Inferno",
	"Inferno",
	"Infinity",
	"Shola Inkosi",
	"Interloper",
	"Invisible Girl",
	"Invisible Woman",
	"Inza",
	"Ion",
	"Iridia",
	"Ironclad",
	"Iron Cross",
	"Iron Fist",
	"Iron Lad",
	"Iron Maiden",
	"Iron Man",
	"Iron Man 2020",
	"Iron Monger",
	"ISAAC",
	"Isbisa",
	"Shirow Ishihara",
	"Isis",
	"the Living Colossus It",
	"J2",
	"Jackal",
	"Jackdaw",
	"Jack Flag",
	"Jack Frost",
	"Jackhammer",
	"Jack-in-the-Box",
	"Jack Kirby",
	"Jack of Hearts",
	"Jack O'Lantern",
	"Jackpot",
	"Jade Dragon",
	"Jaeger",
	"Harald Jaekelsson",
	"Jaguar",
	"J. Jonah Jameson",
	"John Jameson",
	"Dr. Marla Jameson",
	"James Jaspers",
	"Jann",
	"Janus",
	"Jarella",
	"Jaren",
	"Edwin Jarvis",
	"Jason",
	"Jawynn Dueck The Iron christian of Faith",
	"Jazz",
	"Jean Grey",
	"Madison Jeffries",
	"Jeffrey Mace",
	"Jekyll",
	"Abner Jenkins",
	"Jerry Jaxon",
	"Jessica Jones",
	"Jennifer Walters",
	"Jens Meilleur slap shot",
	"Jester",
	"Jigsaw",
	"Jim Hammond",
	"Jimmy Woo",
	"Jocasta",
	"Joe Fixit",
	"Daisy Johnson",
	"John Sublime",
	"Johnny Ohm",
	"Jolt",
	"Jon Spectre",
	"Angelica Jones",
	"jordan seberius",
	"Gabe Jones",
	"Hugh Jones",
	"Rick Jones",
	"Joseph",
	"Conrad Josten",
	"Erik Josten",
	"Madeline Joyce",
	"Joystick",
	"Bonita Juarez",
	"Jubilee",
	"Judas Traveller",
	"Eugene Judd",
	"Jude the Entropic Man",
	"Juggernaut",
	"Jumbo Carnation",
	"Junkpile",
	"Junta",
	"Justice",
	"Justice",
	"Justin Hammer",
	"Kaine",
	"Kala",
	"Jennifer Kale",
	"Kaluu",
	"Kamal",
	"Kamo Tharnn",
	"Kamuu",
	"Garrison Kane",
	"Kang the Conqueror",
	"Kangaroo",
	"Karima Shapandar",
	"Karkas",
	"Karla Sofen",
	"Karma",
	"Karnak",
	"Karnilla",
	"Karolina Dean",
	"Karthon the Quester",
	"Cletus Kasady",
	"Kate Neville",
	"Katu",
	"Benazir Kaur",
	"Ka-Zar",
	"Kehl of Tauran",
	"Keith Kilham",
	"Kem Horkus",
	"Dan Ketch",
	"Robert Kelly",
	"Key",
	"Khaos",
	"Khonshu",
	"Khoryphos",
	"Kiber the Cruel",
	"Kick-Ass",
	"Kid Colt",
	"Kid Nova",
	"Kierrok",
	"Killer Shrike",
	"Zebediah Killgrave",
	"Erik Killmonger",
	"Killpower",
	"Killraven",
	"Kilmer",
	"Kimura",
	"Cessily Kincaid",
	"Jane Kincaid",
	"Benedict Kine",
	"Hannibal King",
	"Kingpin",
	"King Bedlam",
	"Kingo Sunen",
	"Kirigi",
	"Kirtsyn Perrin Short Stop",
	"Kismet",
	"Kismet Deadly",
	"Kiss",
	"Kiwi Black",
	"Kkallakku",
	"Kl'rt",
	"Klaatu",
	"Klaw",
	"Kleinstocks",
	"Knickknack",
	"Misty Knight",
	"Kofi Whitemane",
	"Kogar",
	"Kohl Harder Boulder Man",
	"Korath the Pursuer",
	"Korg",
	"Kormok",
	"Korrek",
	"Korvac",
	"Korvus",
	"Kosmos",
	"Ivan Kragoff",
	"Kraken",
	"Krakkan",
	"Krang",
	"Kraven the Hunter",
	"Alyosha Kravinoff",
	"Sergei Kravinoff",
	"Kristoff Vernard",
	"Kristoff von Doom",
	"Kro",
	"Krystalin",
	"Kubik",
	"Kukulcan",
	"Kurse",
	"Kwannon",
	"Kylun",
	"Kymaera",
	"Lacuna",
	"Lady Deathstrike",
	"Lady Killer",
	"Lady Lark",
	"Lady Lotus",
	"Lady Mandarin",
	"Lady Mastermind",
	"Lady Octopus",
	"La Lunatica",
	"Lancer",
	"Landslide",
	"Cassie Lang",
	"Steven Lang",
	"La Nuit",
	"Larry Bodine",
	"Lament",
	"Lasher",
	"Ebenezer Laughton",
	"Layla Miller",
	"Lazarus",
	"Leader",
	"Leap-Frog",
	"Leash",
	"Remy LeBeau",
	"Leech",
	"Ned Leeds",
	"Lee Forrester",
	"Betty Brant Leeds",
	"Left Hand",
	"Left-Winger",
	"Legacy",
	"Legion",
	"Erik Magnus Lehnsherr",
	"Leir",
	"Lemuel Dorcas",
	"Leo",
	"Leonus",
	"Letha",
	"Levan",
	"Hannah Levy",
	"Alexander Lexington",
	"Lianda",
	"Libra",
	"Lifeforce",
	"Lifeguard",
	"Lifter",
	"Lightbright",
	"Lightmaster",
	"Lighting Rod",
	"Lightspeed",
	"Lila Cheney",
	"Lilandra Neramani",
	"the daughter of Dracula Lilith",
	"Lin Sun",
	"Lonnie Thompson Lincoln",
	"Link",
	"Lionheart",
	"Chan Luichow",
	"Live Wire",
	"Living Brain",
	"Living Colossus",
	"Living Diamond",
	"Living Eraser",
	"Living Hulk",
	"Living Laser",
	"Living Lightning",
	"Living Monolith",
	"Living Mummy",
	"Living Pharaoh",
	"Living Pharaoh",
	"Living Planet",
	"Living Tribunal",
	"Living Totem",
	"Lizard",
	"Llan the Sorcerer",
	"Lloigoroth",
	"Llyra",
	"Llyron",
	"Loa",
	"Carlos Lobo",
	"Lockdown",
	"Lockheed",
	"Lockjaw",
	"Locksmith",
	"Locus",
	"Locust",
	"Lodestone",
	"Logan",
	"Loki",
	"Longneck",
	"Longshot",
	"Looter",
	"Lord Chaos",
	"Lord Dark Wind",
	"Lord Pumpkin",
	"Lorelei",
	"Lorelei II",
	"Lorelei Travis",
	"Lorna Dane",
	"Lorvex",
	"Loss",
	"Chen Lu",
	"Lucas Brand",
	"Lucifer",
	"Ludi",
	"Aleksander Lukin",
	"Willie Lumpkin",
	"Luna",
	"Lunatica",
	"Lunatik",
	"Lupa",
	"Lupo",
	"Lurking Unknown",
	"Lyja",
	"Karl Lykos",
	"Lynx",
	"M",
	"Myron MacLain",
	"Gideon Mace",
	"Jeffrey Mace",
	"Mach-IV",
	"Machine Man",
	"Machinesmith",
	"Machine Teen",
	"Al MacKenzie",
	"Mary \"Skeeter\" MacPherran",
	"Moira MacTaggert",
	"Mad-Dog",
	"Mad Dog Rassitano",
	"Mad Jack",
	"Mad Jim Jaspers",
	"Mad Thinker",
	"Mad Thinker’s Awesome Android",
	"Madam Slay",
	"Madame Hydra",
	"Madame MacEvil",
	"Madame Masque",
	"Madame Menace",
	"Madame Web",
	"Madcap",
	"Artie Maddicks",
	"James Madrox",
	"Madelyne Pryor",
	"Maelstrom",
	"Maestro",
	"Magdalena",
	"Magdalene",
	"Maggott",
	"Magician",
	"Magik",
	"Magilla",
	"Magma",
	"Magneto",
	"Magnum I",
	"Moses Magnum",
	"Magnus",
	"Magus",
	"Magus",
	"Maha Yogi",
	"Mahkizmo",
	"Major Mapleleaf",
	"Makkari",
	"Malekith the Accursed",
	"Malice",
	"Karl Malus",
	"Mammomax",
	"Man-Ape",
	"Man-Beast",
	"Man-Brute",
	"Man-Bull",
	"Man-Eater",
	"Man-Elephant",
	"Man-Killer",
	"Man-Spider",
	"Man-Thing",
	"Man-Wolf",
	"Manbot",
	"Mandarin",
	"Mandrill",
	"Mandroid",
	"Mangle",
	"Mangog",
	"Manikin",
	"Man Mountain Marko",
	"Manslaughter",
	"Manta",
	"Mantis",
	"Mantra",
	"Marc Spector",
	"Mark Gervaisnight shade",
	"Marduk Kurios",
	"Margali Szardos",
	"Maria Hill",
	"Mariko Yashida",
	"James \"Jimmy\" Marks",
	"Cain Marko",
	"Flint Marko",
	"Marlene Alraune",
	"Keen Marlow",
	"Marrina",
	"Marrow",
	"Martha Johansson",
	"Martinex",
	"Marvel Boy",
	"Marvel Boy",
	"Marvel Boy",
	"Marvel Girl",
	"Marvel Man",
	"Mar-Vell",
	"Krista Marwan",
	"Mary Zero",
	"Milos Masaryk",
	"Masked Marauder",
	"Masked Marvel",
	"Masked Rose",
	"Louise Mason",
	"Masque",
	"Mass Master",
	"Master",
	"Master of Vengeance",
	"Master Khan",
	"Master Man",
	"Master Menace",
	"Mastermind",
	"Mastermind of the UK",
	"Mastermind",
	"Master Mold",
	"Master Order",
	"Master Pandemonium",
	"Alicia Masters",
	"Matador",
	"Match",
	"Matsu'o Tsurayaba",
	"Matt Murdock",
	"Mauler",
	"Maur-Konn",
	"Mauvais",
	"Maverick",
	"Max",
	"Maxam",
	"Pietro Maximoff",
	"Wanda Maximoff",
	"Maximus",
	"May Parker",
	"May \"Mayday\" Parker",
	"Mayhem",
	"Henry \"Hank\" McCoy",
	"Namor McKenzie",
	"Meanstreak",
	"Meathook",
	"Mechamage",
	"Medusa",
	"Mekano",
	"Meggan",
	"Meld",
	"Melee",
	"Seamus Mellencamp",
	"Meltdown",
	"Melter",
	"Mentallo",
	"Mentor",
	"Mentor",
	"Mentus",
	"Mephisto",
	"Mercurio",
	"Mercury",
	"Mercy",
	"Merlin",
	"Mesmero",
	"Metal Master",
	"Metalhead",
	"Meteor Man",
	"Meteorite",
	"Meteor Man",
	"Meteorite II",
	"Micro",
	"Microchip",
	"Micromax",
	"Midas",
	"Midgard Serpent",
	"Midnight",
	"Midnight Man",
	"Midnight Sun",
	"Miek",
	"Mikado & Mosha",
	"Mikey",
	"Mikhail Rasputin",
	"Milan",
	"Layla Miller",
	"Mimic",
	"Mimic",
	"Mimir",
	"Mindmeld",
	"Mindworm",
	"Miracle Man",
	"Mirage I",
	"Mirage II",
	"Misfit",
	"Miss America",
	"Missing Link",
	"Mister Buda",
	"Mister Doll",
	"Mister Fear",
	"Mister Hyde",
	"Mister Jip",
	"Mr. M",
	"Mister Machine",
	"Mister One and Mister Two",
	"Mister Sensitive",
	"Mister Sinister",
	"Mister X",
	"Misty Knight",
	"Mist Mistress",
	"Mockingbird",
	"MODAM",
	"MODOK",
	"Modred the Mystic",
	"Mogul of the Mystic Mountain",
	"Moira Brandon",
	"Moira MacTaggert",
	"Mojo",
	"Mole Man",
	"Molecule Man",
	"Molly Hayes",
	"Molten Man",
	"Mondo",
	"Mongoose",
	"Trip Monroe",
	"Monsoon",
	"Monstra",
	"Monstro the Mighty",
	"Moon-Boy",
	"Moon Knight",
	"Moondark",
	"Moondragon",
	"Moonhunter",
	"Danielle Moonstar",
	"Moonstone",
	"Mop Man",
	"Morbius",
	"Karl Mordo",
	"Mordred",
	"Morg",
	"Morgan Le Fay",
	"Morlun",
	"Morning Star",
	"Morph",
	"Morpheus",
	"Moses Magnum",
	"Mother Earth/Mother Nature",
	"Mother Night",
	"Mother Superior",
	"Motormouth",
	"Mountjoy",
	"Mr. Fish",
	"Mr. Justice",
	"Ms. Marvel",
	"Ms. MODOK",
	"Ms. Steed",
	"M-Twins",
	"Multiple Man",
	"Rex Mundi",
	"Ororo Munroe",
	"Matt Murdock",
	"Murmur",
	"Murmur II",
	"Mutant Master",
	"Mutant X",
	"Fred Myers",
	"Mys-Tech",
	"Mysterio",
	"Mystique",
	"N'astirh",
	"N'Gabthoth",
	"N'Garai",
	"Naga",
	"Nameless One",
	"Namor the Sub-Mariner",
	"Namora",
	"Namorita",
	"Nanny",
	"Elektra Natchios",
	"Nate Grey",
	"Nathaniel Essex",
	"Nathaniel Richards",
	"Native",
	"Nebula",
	"Nebulo",
	"Nebulon",
	"Nebulos",
	"Necrodamus",
	"Necromantra",
	"Needle",
	"Luchino Nefaria",
	"Nefarius",
	"Negasonic Teenage Warhead",
	"Nekra",
	"Foggy Nelson",
	"Greer Grant Nelson",
	"Nemesis",
	"Neophyte",
	"Neptune",
	"Network",
	"Neuronne",
	"Neurotap",
	"Kate Neville",
	"Walter Newell",
	"New Goblin",
	"Nezarr the Calculator",
	"NFL Superpro",
	"Nicholas Scratch",
	"Nicholas maunderRed Claw",
	"Nick Fury",
	"Nico Minoru",
	"Nightcrawler",
	"Nighthawk",
	"Night Nurse",
	"The Night Man",
	"Nightmare",
	"Night Rider",
	"Nightshade",
	"Nightside",
	"Night Thrasher",
	"Nightwatch",
	"Nightwind",
	"Nikki",
	"Niles Van Roekel",
	"Nimrod",
	"Ningal",
	"Adri Nital",
	"Taj Nital",
	"Nitro",
	"Kiden Nixon",
	"MN-E (Ultraverse)",
	"Nobilus",
	"Peter Noble",
	"Nocturne",
	"Nocturne",
	"Noh-Varr",
	"Nomad",
	"Norman Osborn",
	"Norns",
	"Norrin Radd",
	"Dakota North",
	"Northstar",
	"Nosferata",
	"Nova",
	"Nova-Prime",
	"Cassandra Nova",
	"Novs",
	"Michael Nowman",
	"Nox",
	"Nth Man: the Ultimate Ninja",
	"Nth Man",
	"Nuke - Frank Simpson",
	"Nuke - Squadron Supreme member",
	"Nuklo",
	"the Living Darkness Null",
	"Numinus",
	"Nut",
	"Alfie O'Meggan",
	"Solomon O'Sullivan",
	"Obituary",
	"Obliterator",
	"Oblivion",
	"Occulus",
	"Ocean",
	"Ocelot",
	"Dr. Otto Octavius",
	"Oddball",
	"Odin",
	"Aleta Ogord",
	"Ogre",
	"Ogress",
	"Miguel O'Hara",
	"Omen",
	"Omega Red",
	"Omega I",
	"Omega the Unknown",
	"Omerta",
	"One Above All",
	"Oneg the Prober",
	"Onslaught",
	"Onyxx",
	"Ooze",
	"Optoman",
	"Oracle",
	"Orator",
	"Orb",
	"Orbit",
	"Orchid",
	"Ord",
	"Order",
	"Orikal",
	"Orka",
	"Orphan",
	"Orphan-Maker",
	"Harry Osborn",
	"Norman Osborn",
	"Osiris",
	"Outlaw",
	"Outrage",
	"Overkill",
	"Overmind",
	"Overrider",
	"Ozone",
	"Owl",
	"Ox",
	"Ozymandias",
	"Karen Page",
	"Paibo",
	"Paladin",
	"Paradigm",
	"Paragon",
	"Paralyzer",
	"Paris",
	"Ben Parker",
	"Mary Jane Parker",
	"May Parker",
	"Richard Parker",
	"Peter Parker",
	"Arthur Parks",
	"Pasco",
	"Paste-Pot Pete",
	"Patch",
	"Pathway",
	"Patriot I",
	"Patriot II",
	"Paul Patterson",
	"Payback",
	"Reeva Payge",
	"Frank Payne",
	"Peace Monger",
	"Peepers",
	"Penance",
	"Penance II",
	"Peregrine",
	"Perfection",
	"Perseus",
	"Persuader",
	"Persuasion",
	"Perun",
	"Pete Wisdom",
	"Peter Criss",
	"Dominic Petros",
	"Peter Petruski",
	"Phade",
	"Phantazia",
	"Phantom Blonde",
	"Phantom Eagle",
	"Phantom Rider",
	"Phalanx",
	"Phage",
	"Phastos",
	"Phat",
	"Ellie Phimster",
	"Phoenix",
	"Photon",
	"Phyla-Vell",
	"Alexander Goodwin Pierce",
	"Piledriver",
	"Pipeline",
	"Piper",
	"Pip the Troll",
	"Piper",
	"Piranha",
	"Pisces",
	"Pistol",
	"Desmond Pitt",
	"Pixie",
	"Pixx",
	"Plague",
	"Plantman",
	"Plasma",
	"Plazm",
	"Plug",
	"Plunderer",
	"Pluto",
	"Poison",
	"Polaris",
	"Poltergeist",
	"Porcupine",
	"Portal",
	"Possessor",
	"Postman",
	"Postmortem",
	"Virginia \"Pepper\" Potts",
	"Poundcakes",
	"Powderkeg",
	"Alex Power",
	"Jack Power",
	"James Dr. Power",
	"Julie Power",
	"Katie Power",
	"Margaret Power",
	"Power Broker",
	"Power Man",
	"Power Princess",
	"Power Skrull",
	"Powerpax",
	"Powerhouse",
	"Presence",
	"Pressure",
	"Prester John",
	"Martin Preston",
	"Pretty Persuasions",
	"Preview",
	"Primal",
	"Prime",
	"Prime Mover",
	"Primevil",
	"Primus",
	"Princess Python",
	"Proctor",
	"Prodigy",
	"Professor Power",
	"Professor X",
	"The Profile",
	"Projector",
	"Prometheus",
	"Protector",
	"Proteus",
	"Prototype",
	"James Proudstar",
	"John Proudstar",
	"Prowler",
	"Katherine \"Kitty\" Pryde",
	"Psi-Lord",
	"Psyche",
	"Psycho-Man",
	"Psyklop",
	"Psylocke",
	"Puck",
	"Puff Adder",
	"Puishannt",
	"Pulse",
	"Puma",
	"Punchout",
	"Punisher",
	"Punisher I",
	"Punisher 2099",
	"Puppet Master",
	"Purge",
	"Purple Girl",
	"Purple Man",
	"Pyre",
	"Pyro",
	"Quagmire",
	"Quantum",
	"Quasar",
	"Quasar II",
	"Quasimodo",
	"Quicksand",
	"Quicksilver",
	"Quincy Harker",
	"Quentin Beck",
	"Quentin Quire",
	"Raa of the Caves",
	"Rachel van Helsing",
	"Norrin Radd",
	"Radioactive Man",
	"Radian",
	"Radion the Atomic Man",
	"Radius",
	"Rafferty",
	"Rage",
	"Raggadorr",
	"Rainbow",
	"Rama-Tut",
	"Raman",
	"Ramrod",
	"Doug Ramsey",
	"Ramshot",
	"Rancor",
	"Daniel Rand",
	"Randall Shire",
	"Random",
	"Ranger",
	"Calvin Rankin",
	"Ransak the Reject",
	"Monica Rappaccini",
	"Illyana Rasputin",
	"Mikhail Rasputin",
	"Piotr Rasputin",
	"Rattler",
	"Ravage 2099",
	"Raving Beauty",
	"Rawhide Kid",
	"Rax",
	"Mark Raxton",
	"Frankie Raye",
	"Raza",
	"Razor Fist",
	"Razorback",
	"Rebel",
	"Reaper",
	"Recorder",
	"Red Ghost",
	"Red Guardian",
	"Red Lotus",
	"Redneck",
	"Red Nine",
	"Red Raven",
	"Red Ronin",
	"Red Shift",
	"Red Skull",
	"Red Skull II",
	"Red Wolf",
	"Redeemer",
	"Redwing",
	"Reignfire",
	"Ben Reilly",
	"Reject",
	"Remnant",
	"Remy LeBeau",
	"Reptyl",
	"Revanche",
	"Cecelia Reyes",
	"Katherine Reynolds",
	"Rhiannon",
	"Rhino",
	"James Rhodes",
	"Ricadonna",
	"Richard Rider",
	"Jonathan Richards",
	"Susan Richards",
	"Rick Jones",
	"Ricochet",
	"Rictor",
	"Richard Rider",
	"Rigellian Recorder",
	"Right-Winger",
	"Ringer",
	"Ringleader",
	"Ringmaster",
	"Ringo Kid",
	"Rintrah",
	"Riot",
	"Riot Grrl",
	"Ripfire",
	"Rl'nnd",
	"Robbie Robertson",
	"Robert Kelly",
	"Rocket Raccoon",
	"Rocket Racer",
	"Rock",
	"Rock Python",
	"Rodstvow",
	"Steve Rogers",
	"Rogue",
	"Roma",
	"Rom the Spaceknight",
	"Ronan the Accuser",
	"Rose",
	"Marsha Rosenberg",
	"Arkady Rossovich",
	"Roughhouse",
	"Roulette",
	"Royal Roy",
	"Ruby Thursday",
	"Ruckus",
	"Rune",
	"Runner",
	"Rush",
	"The Russian",
	"Rusty Collins",
	"Ryder",
	"John Ryker",
	"S'byll",
	"Sabra",
	"Sabreclaw",
	"Sabretooth",
	"Sack",
	"Sage",
	"Sagittarius",
	"Saint Anna",
	"Saint Elmo",
	"Sally Floyd",
	"Salvo",
	"Leonard Samson",
	"James Sanders",
	"Basil Sandhurst",
	"Sandman",
	"Sangre",
	"Miguel Santos",
	"Sasquatch",
	"Satana",
	"Satannish",
	"Saturnyne",
	"Sauron",
	"Savage Steel",
	"Sam Sawyer",
	"Samuel \"Starr\" Saxon",
	"Sayge",
	"Scaleface",
	"Scalphunter",
	"Scanner",
	"Scarecrow",
	"Scarecrow II",
	"Scarlet Beetle",
	"Scarlet Centurion",
	"Scarlet Scarab",
	"Scarlet Spider",
	"Scarlet Spiders",
	"Scarlet Witch",
	"Mark Scarlotti",
	"Schemer",
	"Johann Schmidt",
	"Herman Schultz",
	"Silver Scorpion",
	"Scimitar",
	"Scintilla",
	"Scorcher",
	"Scorpia",
	"Scorpio",
	"Scorpion",
	"Scourge of the Underworld",
	"Scrambler",
	"Nicholas Scratch",
	"Scream",
	"Screaming Mimi",
	"Screech",
	"Scrier",
	"Sea Urchin",
	"Sebastian Shaw",
	"Seeker",
	"Amanda Sefton",
	"Sekhmet",
	"Selene",
	"Senor Muerte",
	"Sentry",
	"Senator Robert Kelly",
	"Sepulchre",
	"Sergeant Fury",
	"Serpentina",
	"Sersi",
	"Set",
	"Seth",
	"Shadow-Hunter",
	"Shadow King",
	"Shadow Slasher",
	"Shadowcat",
	"Shadowmage",
	"Shadrac",
	"Shalla-Bal",
	"Shaman",
	"Shamrock",
	"Shang-Chi",
	"Shanga",
	"Shanna the She-Devil",
	"Gregor Shapanka",
	"Shaper of Worlds",
	"Shard",
	"Sharon Friedlander",
	"Shathra",
	"Shatter",
	"Shatterfist",
	"Shatterstar",
	"Sebastian Shaw",
	"Shinobi Shaw",
	"She-Hulk",
	"She-Thing",
	"She-Venom",
	"Shellshock",
	"Shen Kuei",
	"Shinchuko Lotus",
	"Shriker",
	"Shingen Harada",
	"Shiva",
	"Shiver Man",
	"Shocker",
	"Shockwave",
	"Shola Inkosi",
	"Shooting Star",
	"Shotgun",
	"Shriek",
	"Shroud",
	"Shrunken Bones",
	"Shuma-Gorath",
	"Sidewinder",
	"Siege",
	"Sif",
	"Sigmar",
	"Sigyn",
	"Sikorsky",
	"Raymond Sikorsky",
	"Samuel Silke",
	"Silly Seal",
	"Silhouette",
	"Silver",
	"Silver Dagger",
	"Silver Fox",
	"Silver Sable",
	"Silver Samurai",
	"Silver Squire",
	"Silver Surfer",
	"Silverclaw",
	"Silvermane",
	"Frank Simpson",
	"Ezekiel Sims",
	"Sin",
	"Sin-Eater",
	"Nekra Sinclar",
	"Rahne Sinclair",
	"Sinister",
	"Sir Steel",
	"Siryn",
	"Sise-Neg",
	"Skein",
	"Skids",
	"Skin",
	"Skinhead",
	"Skull the Slayer",
	"Skullfire",
	"Skullcrusher",
	"Skunge the Laxidazian Troll",
	"Skyhawk",
	"Skywalker",
	"Slab",
	"Frederick Slade",
	"Hamilton Slade",
	"Slapstick",
	"Sleek",
	"Sleeper",
	"Sleepwalker",
	"Slick",
	"Slipstream",
	"Sligguth",
	"Slither",
	"Sludge",
	"Slug",
	"Sluggo",
	"Sluk",
	"Slyde",
	"Marrina Smallwood",
	"Smart Alec",
	"Smartship Friday",
	"Smasher",
	"Dmitri Smerdyakov",
	"Tabitha Smith",
	"Samuel Smithers",
	"Smuggler I",
	"Smuggler II",
	"Alistair Smythe",
	"Spencer Smythe",
	"Snowbird",
	"Snowfall",
	"Karla Sofen",
	"Solara",
	"Solarman",
	"Solarr",
	"Solo",
	"Soldier X",
	"Solitaire",
	"Solo",
	"Songbird",
	"Son of Satan",
	"Soulfire",
	"Space Phantom",
	"Space Turnip",
	"Marc Spector",
	"Spectra",
	"Spectral",
	"Specialist",
	"Speed",
	"Speed Demon",
	"Speedball",
	"Speedo",
	"Spellbinder",
	"Spellcheck",
	"Sphinx",
	"Sphinxor",
	"Spider Doppelganger",
	"Spider-Girl",
	"Spider-Ham",
	"Spider-Man",
	"Spider-Slayer",
	"Spider-Woman",
	"Spidercide",
	"Spike",
	"Spike Freeman",
	"Spinnerette",
	"Spiral",
	"Spirit of '76",
	"Spitfire",
	"Spoilsport",
	"Spoor",
	"Spot",
	"Sprite",
	"Sputnik",
	"Spyder",
	"Spymaster",
	"Spyne",
	"Squirrel Girl",
	"Squidboy",
	"Claudette St. Croix",
	"Marius St. Croix",
	"Monet St. Croix",
	"Nicole St. Croix",
	"George Stacy",
	"Gwen Stacy",
	"Stacy X",
	"Stained Glass Scarlet",
	"Stakar",
	"Stallior",
	"Ezekiel Stane",
	"Obadiah Stane",
	"Star-Dancer",
	"Star-Lord",
	"Star Stalker",
	"Star Thief",
	"Starbolt",
	"Stardust",
	"Starfox",
	"Starhawk",
	"Starlight",
	"Arno Stark",
	"Tony Stark",
	"Starr the Slayer",
	"Starshine",
	"Jonothon Starsmore",
	"Starstreak",
	"Stature",
	"Steel Raven",
	"Steel Serpent",
	"Steel Spider",
	"Stegron",
	"Chase Stein",
	"Stellaris",
	"Stem Cell",
	"Stentor",
	"The Amazing Tanwir Ahmed",
	"The Stepford Cuckoos",
	"Stephen Colbert",
	"Stevie Hunter",
	"Steven Lang",
	"Stanley Stewart",
	"Stick",
	"Stiletto",
	"Stilt-Man",
	"Stinger",
	"Stingray",
	"Stitch",
	"Stone",
	"Stonecutter",
	"Stonewall",
	"Storm",
	"Franklin Storm",
	"Johnny Storm",
	"Susan Storm",
	"Stephen Strange",
	"Victor Strange",
	"Stranger",
	"Stratosfire",
	"Straw Man",
	"Strobe",
	"Strong Guy",
	"Strongarm",
	"Baron Strucker",
	"Stryfe",
	"William Stryker",
	"Stunner",
	"Stuntmaster",
	"Stygorr",
	"Stygyro",
	"Styx and Stone",
	"John Sublime",
	"Sub-Mariner",
	"Sugar Man",
	"Suicide",
	"Sultan",
	"Alexander Summers",
	"Christopher Summers",
	"Gabriel Summers",
	"Rachel Summers",
	"Scott Summers",
	"Sunder",
	"Sundragon",
	"Sunfire",
	"Sunpyre",
	"Sunset Bain",
	"Sunspot",
	"Sunstreak",
	"Sunstroke",
	"Sunturion",
	"Sun Girl",
	"Super Rabbit",
	"Super-Adaptoid",
	"Supercharger",
	"Superia",
	"Super-Nova",
	"SuperPro",
	"Super Rabbit",
	"Super Sabre",
	"Super-Skrull",
	"Supernalia",
	"Suprema",
	"Supreme Intelligence",
	"Supremor",
	"Surge",
	"Surtur",
	"Sushi",
	"Svarog",
	"Swarm",
	"Sweetface",
	"Swordsman",
	"S'ym",
	"Sybil Dorn",
	"The Symbiote",
	"Synch",
	"Aleksei Sytsevich",
	"Jimaine Szardos",
	"Margali Szardos",
	"Tag",
	"Tagak the Leopard Lord",
	"Tailhook",
	"Tantra",
	"Glenn Talbot",
	"Talisman",
	"Tamara Rahn",
	"Tana Nile",
	"Tarantula",
	"George Tarleton",
	"Black Jack Tarr",
	"Tarot",
	"Tartarus",
	"Taskmaster",
	"Tatterdemalion",
	"Tattletale",
	"Tattoo",
	"Taurus",
	"General Orwell Taylor",
	"Techno",
	"Tefral the Surveyor",
	"Tempest",
	"Tempest",
	"Tempo",
	"Tempus",
	"Temugin",
	"Tenpin",
	"Termagaira",
	"Terminator",
	"Terminatrix",
	"Terminus",
	"Terrax the Tamer",
	"Terraxia",
	"Terror",
	"Tess-One",
	"Tessa",
	"Tether",
	"Tethlam",
	"Texas Twister",
	"Thakos",
	"Thane Ector",
	"Thanos",
	"Thena",
	"Thermo",
	"Thing",
	"Thinker",
	"Thin Man",
	"Thirty-Three",
	"Thog",
	"Everett Thomas",
	"Flash Thompson",
	"Thor",
	"Thor Girl",
	"Thornn",
	"3-D Man",
	"Threnody",
	"Tom Thumb",
	"Thumbelina",
	"Thunderball",
	"Thunderbird",
	"Thunderbolt",
	"Thunderclap",
	"Thunderfist",
	"Thunderstrike",
	"Thundra",
	"Maynard Tiboldt",
	"Tiboro",
	"Tiger Shark",
	"Tigra",
	"Timberius",
	"Time Bomb",
	"Timeshadow",
	"Timeslip",
	"Tinkerer",
	"Titan",
	"Titania",
	"Titanium Man",
	"Toad",
	"Toad-In-Waiting",
	"Mark Todd",
	"Tom Thumb",
	"Tomazooma",
	"Tombstone",
	"Tommy",
	"Tommy Lightning",
	"Tomorrow Man",
	"Adrian Toomes",
	"Topaz",
	"Yuri Topolov",
	"Topspin",
	"Torgo the Vampire",
	"Torgo of Mekka",
	"Toro",
	"Torpedo",
	"Torrent",
	"Torso",
	"Tower",
	"Toxin",
	"Mortimer Toynbee",
	"Trader",
	"Trapper",
	"Trapster",
	"Carolyn Trainer",
	"Chloe Tran",
	"T-Ray",
	"Tremolo",
	"Trevor Fitzroy",
	"Tri-Man",
	"Triathlon",
	"Trick Shot",
	"Trioccula",
	"Triton",
	"Troll",
	"Arlette Truffaut",
	"Trump",
	"Tugun",
	"Tuc",
	"Tumbler",
	"Tundra",
	"Turac",
	"Turbo",
	"Turner D. Century",
	"Tusk",
	"Tutinax the Mountain-Mover",
	"Two-Gun Kid",
	"Elizabeth Twoyoungmen",
	"Michael Twoyoungmen",
	"Tyger Tiger",
	"Typeface",
	"Typhoid",
	"Typhoid Mary",
	"Typhon",
	"Tyr",
	"Tyrak",
	"Tyrannosaur",
	"Tyrannus",
	"Tyrant",
	"Tzabaoth",
	"Uatu",
	"U-Go Girl",
	"Ulik",
	"Ultimo",
	"Ultimus",
	"Ultra-Marine",
	"Ultragirl",
	"Ultron",
	"Umbo",
	"U-Man",
	"Umar",
	"Uncle Ben Parker",
	"Unicorn",
	"Uni-Mind",
	"Union Jack",
	"Unseen",
	"Unthinnk",
	"Unus the Untouchable",
	"Unuscione",
	"Carmella Unuscione",
	"Angelo Unuscione",
	"Ursa Major",
	"Urthona",
	"USAgent",
	"Ben Urich",
	"Phil Urich",
	"Ulysses",
	"Utgard-Loki",
	"Vagabond",
	"Vague",
	"Vakume",
	"Valentina Allegra de Fontaine",
	"Valerie Cooper",
	"Valinor",
	"Valkin",
	"Valkyrie",
	"Valtorr",
	"Vamp",
	"Vampire by Night",
	"Janet van Dyne",
	"Katrina Luisa van Horne",
	"Cornelius van Lunt",
	"Vance Astro",
	"Vanguard",
	"Vanisher",
	"Vapor",
	"Vargas",
	"Varnae",
	"Vashti",
	"Wendell Vaughn",
	"Vavavoom",
	"Vector",
	"Vegas",
	"Veil",
	"Veil",
	"Bram Velsing",
	"Vengeance",
	"Venom",
	"Venom",
	"Venomm",
	"Sharon Ventura",
	"Venus",
	"Venus Dee Milo",
	"Veritas",
	"Vermin",
	"Vertigo",
	"Vesta",
	"Vibraxas",
	"Vibro",
	"Victor Mancha",
	"Victor von Doom",
	"Victorius",
	"Vidar",
	"Vincente",
	"Vindaloo",
	"Vindicator",
	"Viper",
	"Virako",
	"Virgo",
	"Vishanti",
	"Visimajoris",
	"Vision",
	"Vivisector",
	"Vixen",
	"Volcana",
	"Volla",
	"Volpan",
	"Volstagg",
	"Claire Voyant",
	"Vulcan",
	"Vulture",
	"Kurt Wagner",
	"Talia Josephine Wagner",
	"John Walker",
	"Mary Walker",
	"Patsy Walker",
	"Wallflower",
	"Jennifer Walters",
	"War",
	"War V",
	"War Eagle",
	"War Machine",
	"Warbird",
	"Warhawk",
	"Warlock",
	"Adam Warlock",
	"Warpath",
	"Miles Warren",
	"Warrior Woman",
	"Warstar",
	"Warstrike",
	"Warwolves",
	"Scott Washington",
	"Washout",
	"Wasp",
	"Watcher",
	"Water Wizard",
	"Watoomb",
	"Mary Jane Watson",
	"Weapon X",
	"Wendigo",
	"Werewolf by Night",
	"Western Kid",
	"Whiplash",
	"Whirlwind",
	"Whistler",
	"White Fang",
	"Aelfyre Whitemane",
	"Kofi Whitemane",
	"Whiteout",
	"White Pilgrim",
	"White Rabbit",
	"White Queen",
	"White Tiger",
	"Debra Whitman",
	"Whizzer",
	"Wiccan",
	"Wicked",
	"Widget",
	"Wild Child",
	"Wildboys",
	"Alex Wilder",
	"Wildpride",
	"Wildside",
	"Wild Thing",
	"Will o' the Wisp",
	"Eric Williams",
	"Simon Williams",
	"Sam Wilson",
	"Wade Wilson",
	"Wind Dancer",
	"Wind Warrior",
	"Windeagle",
	"Windshear",
	"Colleen Wing",
	"Wyatt Wingfoot",
	"Winter Soldier",
	"The Wink",
	"Winky Man",
	"Pete Wisdom",
	"Romany Wisdom",
	"Witchfire",
	"Bentley Wittman",
	"Wizard",
	"Wiz Kid",
	"Wolf",
	"Wolfsbane",
	"Wolverine",
	"Wonder Man",
	"Wong",
	"Jimmy Woo",
	"Woodgod",
	"Worm",
	"Warren III Worthington",
	"Wraith",
	"Wrath",
	"Wrecker",
	"Wreckage",
	"Mr. Wu",
	"Wundarr the Aquarian",
	"Herbert Edgar Wyndham",
	"Wysper",
	"X-23",
	"X-Cutioner",
	"X-Man",
	"X-Treme",
	"Xandu",
	"Charles Xavier",
	"Xavin",
	"Xemnu the Titan",
	"Xemu",
	"Xi'an Chi Xan",
	"Xorn",
	"Xorr the God-Jewel",
	"X-Ray",
	"Y'Garon",
	"Yandroth",
	"Mariko Yashida",
	"Yellow Claw",
	"Yellowjacket",
	"Yeti",
	"Yith",
	"Ymir",
	"Yondu",
	"Yrial",
	"Yukio",
	"Yuriko Oyama",
	"Yukon Jack",
	"Zabu",
	"Zach",
	"Zaladane",
	"Zarathos",
	"Zarek",
	"the Tomorrow Man Zarrko",
	"Zartra",
	"Zebediah Killgrave",
	"Zeitgeist",
	"Heinrich Zemo",
	"Helmut Zemo",
	"Zero",
	"Zero-G",
	"Zeus",
	"Ziggy Pig",
	"Zip-Zap",
	"Zodiak",
	"Arnim Zola",
	"Zom",
	"Zombie",
	"Zuras",
	"Zzzax"
];

NameGenerator.get_random_name = function() {
	return name_list[Math.floor(Math.random() * name_list.length)];
};
